### PR TITLE
updates patreon link to new page

### PR DESCRIPTION
**Pull request by tdkohlbeck**
marquiskurt -> hyperspacedev

---
name: Pull request
about: Create a pull request to help us improve the code
title: "Request title"

---

This PR makes the following changes:

### CODE REVIEW

**Comment by alicerunsonfedora** [comment]
Looks like the only checks that failed were on the macOS client, but it shouldn't matter since you've only modified the README. I'll go ahead and approve and merge these changes.

Thanks for the catch.

**Comment by tdkohlbeck** [comment]
I'm super green when it comes to contributing to open source, how would I go about fixing the failed check? Or where can I find this information myself?

Love the project! I hope to be submitting more pull requests in the future :)

**Comment by alicerunsonfedora** [comment]
Don’t worry about the failed check, it’s mostly just a CI issue because of certificate signing and what-not

**Comment by tdkohlbeck** [comment]
cool, thanks!

**Pull request merged**
