### PR TITLE
[HD-29] Close drawer after clicking a menu item

### PR DESCRIPTION
**Pull request by travisk-codes**
This PR makes the following changes:
- Changes Drawer onClose prop to onClick
- Implements #139 

Not sure if removing onClose breaks anything, please let me know if (you think) it does. Thanks!

### CODE REVIEW

**Comment by alicerunsonfedora** [comment]
I've also changed this PR to go into the `develop-1.1.0-beta2` branch so that we can get feedback on this behavior change in the next beta.

**Comment by alicerunsonfedora** [comment]
This PR should also fix [HD-29] in our internal tracker.

**Comment by alicerunsonfedora** [comment]
Was almost going to merge this but noticed it's coming from the same branch as #143. Not sure if this is going to cause a merging issue.

**Comment by travisk-codes** [comment]
Oh no! Is this something that I can/should fix on my end? A new pull request? (still new to this stuff)

**Comment by alicerunsonfedora** [comment]
If this is all from the same branch, we can just make sure that your newest PR covers both issues and that we don't merge this one should we do it that way. I'll make a note on the other PR.

**Comment by travisk-codes** [comment]
Cool, I'll be double checking commits before submitting my next PR. This is how one learns right? I think I just didn't delete my fork after the first PR...

**Comment by alicerunsonfedora** [comment]
Totally fine! We usually make a separate branch and then perform a PR, and I think it might translate in terms of how it's done with forks. You should be able to make a new branch from the branch we're working on (`develop-1.1.0-beta2`) on your fork and then make a PR to upstream that way.

**Comment by alicerunsonfedora** [comment]
Looks like it didn't work like I expected, so I took a look at what changed and manually applied it. Going to close this now.

**Pull request closed without merging**
