### PR TITLE
[HD-38] Enable subdirectory support

### PR DESCRIPTION
**Pull request by alicerunsonfedora**
This PR makes the following changes:

- Adds documentation to the Welcome page
- Changes redirect after fetching token to the `config.location` address if it isn't defined as `dynamic` or `desktop`
- Changes `checkForTokens` so that it properly reads the config and not the state since this method is called in `componentDidMount`
- Fixes and implements [HD-38] and #152 

- [ ] This is a release check.

[HD-38]: https://hyperspacedev.atlassian.net/browse/HD-38

### CODE REVIEW

**Comment by alicerunsonfedora** [comment]
Recommended method of testing:

1. Build the copy of Hyperspace as if distributing the static files.
2. Create an empty folder and a subdirectory inside of it.
3. Copy the static files over to the subdirectory.
4. Change the location in config to `http://localhost:5000/<subdirectory_name>`
5. Use a site serving tool like npm's serve or SiteJS to serve the root directory, and make sure the port is set to `5000`.
6. Proceed to login at the subdirectory by going to http:\/\/localhost:5000/<subdirectory_name>

**Comment by travisk-codes** [comment]
(Approx) steps taken from dir `hyperspace`
- `npm run build`
- `mkdir ../test`
- `mkdir ../test/subdir`
- `cp -r build/* ../test/subdir`
- edit `config.json` to point to `http://localhost:5000/subdir`
- `npx serve -l 5000 ../test`

Only note: welcome page loads from `localhost:5000/subdir` but after authorization, page redirects to `localhost:5000/subdir?code=[code]` which doesn't work. Adding a slash after `subdir` makes it work though. Is this behavior good enough?

**Comment by alicerunsonfedora** [comment]
I think we run into issues where the code goes as Mastodon's callback system for OAuth gets a bit wonky when seeing the hash sign (`#`), but I think we want to make sure that slash is added at the end to ensure that it works.

**Comment by alicerunsonfedora** [comment]
Going to re-request a review here. Updated `getConfig` to add a backslash if there's not one in the location, but put a warning in the console.

**Comment by travisk-codes** [comment]
Navigating to `http://localhost:5000/subdir` doesn't work but adding a trailing slash does. The behavior is the same regardless of whether the `location` property in `test/subdir/config.json` has a trailing slash or not (`http://localhost:5000/subdir[ '' | '/']`)

Hopefully I'm not just causing confusion on my end with folder structure or something...

**Comment by alicerunsonfedora** [comment]
Isn't that more of an web server config thing, tough? I thought browsers interpreted `https://localhost:5000/server` and `https://localhost:5000/server/` differently unless the web server rules tell it that they're the same thing, like with `.htaccess`...

**Pull request merged**
